stages:
  - test
  - deploy

test:
  tags:
    - self-hosted
  stage: test
  script:
    - docker compose -f docker-compose.yml -f docker-compose.test.yml -p test-api down || true
    - docker compose -f docker-compose.yml -f docker-compose.test.yml -p test-api up --build --exit-code-from api

deploy:
  dependencies:
    - test
  stage: deploy
  only:
    - main
  tags:
    - self-hosted
  script:
    - cd /home/gitlab-runner/backend
    - git pull
    - docker compose -f docker-compose.yml -f docker-compose.prod.yml -p backend up -d --build
    - sleep 5
    - docker logs -n 30 -t backend-api-1
