services:
  api:
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
  postgres:
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data