services:
  api:
    environment:
      - SERVER_URLS=https://{{sensitive_data}}
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PUBLIC_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - api
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./server.crt:/etc/nginx/server.crt
      - ./server.key:/etc/nginx/server.key
    ports:
      - 443:443
    networks:
      - backend
