[tool.ruff]
target-version = 'py311'
line-length = 88
force-exclude = true

[tool.ruff.lint]
select = [
    "F",  # Pyflakes
    "W",  # pycodestyle
    "E",  # pycodestyle
    "C90",  # mccabe
    "I",  # isort
    "N",  # PEP8 naming
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "COM",  # flake8-commas
    "Q",  # flake8-quotes
    "TID",  # flake8-tidy-imports
]
ignore = [
    "COM812",  # missing-trailing-comma
    "PLR0913", # too-many-arguments
    "B008",  # function-call-in-default-argument
    "TID252",  # relative-imports
    "W291",  # trailing-whitespace
#    "F401",  # unused-import
]
exclude = [
    "alembic/*",
]
